const ERROR_HEADER = '[ERROR]';

export const MESSAGE = Object.freeze({
  OUTPUT_MESSAGE: '결과 : ',
  INPUT_MESSAGE: '덧셈할 문자열을 입력해 주세요. \n',

  ERROR_MESSAGE_NOT_INCLUDE_SEPARATOR: `${ERROR_HEADER} 사용자 정의 구분자가 포함되어 있지 않습니다.`,
  ERROR_MESSAGE_CANNOT_CONVERT_NUMBER: `${ERROR_HEADER} 숫자로 변환할 수 없는 값이 포함되어 있습니다.`,
  ERROR_MESSAGE_INVALID_INPUT: `${ERROR_HEADER} 입력값이 올바르지 않습니다.`,
  ERROR_MESSAGE_INVALID_NUMBER_LENGTH: `${ERROR_HEADER} 숫자의 길이가 올바르지 않습니다.`,
  ERROR_MESSAGE_INVALID_NUMBER_RANGE: `${ERROR_HEADER} 숫자의 범위가 올바르지 않습니다.`,
  ERROR_MESSAGE_INVALID_NUMBER_NEGATIVE: `${ERROR_HEADER} 음수인 숫자는 입력할 수 없습니다.`,
  ERROR_MESSAGE_INVALID_SEPARATOR_LENGTH: `${ERROR_HEADER} 구분자의 길이가 올바르지 않습니다.`,
  ERROR_MESSAGE_INVALID_SEPARATOR_TYPE: `${ERROR_HEADER} 타입이 올바르지 않습니다.`,
  ERROR_MESSAGE_INVALID_VALUE_LENGTH: `${ERROR_HEADER} 값의 길이가 올바르지 않습니다.`,
  ERROR_MESSAGE_INVALID_VALUE_NUMBER: `${ERROR_HEADER} 값이 모두 숫자입니다.`,
  ERROR_MESSAGE_INVALID_VALUE_STRING: `${ERROR_HEADER} 값이 모두 문자열입니다.`,
});
