const INPUT_MESSAGE = "덧셈할 문자열을 입력해 주세요.\n";
const OUTPUT_MESSAGE = "결과 : ";

const DEFAULT_DELIMITER = [",", ":"];
const CUSTOM_DELIMITER_START = "//";
const CUSTOM_DELIMITER_END = "\\n";

export {
  INPUT_MESSAGE,
  OUTPUT_MESSAGE,
  DEFAULT_DELIMITER,
  CUSTOM_DELIMITER_START,
  CUSTOM_DELIMITER_END,
};
